<?php
declare(strict_types=1);
define('CMS_ROOT',sys_get_temp_dir().'/cms-seo-render-'.bin2hex(random_bytes(4)));mkdir(CMS_ROOT,0700,true);require dirname(__DIR__).'/system/core/Bootstrap/autoload.php';
use Cms\Core\Config\Settings;use Cms\Core\Content\{ContentRepository,ContentTypeRegistry,ContentFrontController};use Cms\Core\Migration\MigrationRunner;use Cms\Core\Logging\FileLogger;
function cpdir(string$a,string$b):void{mkdir($b,0700,true);foreach(scandir($a)as$f){if($f==='.'||$f==='..')continue;is_dir($a.'/'.$f)?cpdir($a.'/'.$f,$b.'/'.$f):copy($a.'/'.$f,$b.'/'.$f);}}
foreach(['default','daiying_media','safe']as$t)cpdir(dirname(__DIR__).'/content/themes/'.$t,CMS_ROOT.'/content/themes/'.$t);
$p=new PDO('sqlite:'.CMS_ROOT.'/cms.sqlite');$p->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$m=[];foreach(glob(dirname(__DIR__).'/system/migrations/*.php')as$f)$m[]=require$f;(new MigrationRunner($p,$m))->run();$r=new ContentRepository($p,ContentTypeRegistry::defaults(),[],CMS_ROOT);$id=$r->create('article','Article','seo-article',[],'published',['seo_title'=>'Independent title','seo_description'=>'Independent description','seo_keywords'=>'article, unique','canonical_url'=>'https://isolated.example/articles/seo-article'],['News'],['CMS']);
foreach(['default','daiying_media']as$t){$s=Settings::fromArray(['app'=>['version'=>'1.2.81'],'database'=>['dsn'=>'sqlite:'.CMS_ROOT.'/cms.sqlite'],'site'=>['name'=>'Site','url'=>'https://isolated.example'],'theme'=>['active'=>$t,'settings'=>[$t=>['seo_keywords'=>'global keywords']]]]);$controller=new ContentFrontController(CMS_ROOT,$s,new FileLogger(CMS_ROOT.'/log'));
$html=$controller->article(new \Cms\Core\Http\Request('GET','/articles/seo-article'))->body();foreach(['name="keywords" content="article, unique"','<title>Independent title</title>','name="description" content="Independent description"','rel="canonical" href="https://isolated.example/articles/seo-article"']as$needle){if(!str_contains($html,$needle))throw new RuntimeException($t.' missing '.$needle);}if(substr_count($html,'name="keywords"')!==1)throw new RuntimeException('duplicate keywords');echo "[PASS] $t actual article HTML keywords/title/description/canonical\n";
$r->patch($id,['meta'=>['seo_keywords'=>'']]);$html=$controller->article(new \Cms\Core\Http\Request('GET','/articles/seo-article'))->body();if(!str_contains($html,'name="keywords" content="global keywords"'))throw new RuntimeException($t.' global fallback missing');echo "[PASS] $t global fallback\n";$r->patch($id,['meta'=>['seo_keywords'=>'article, unique']]);}
