<?php
declare(strict_types=1);use Cms\Core\Theme\TemplateContext;/** @var TemplateContext $context */
require_once dirname(__DIR__).'/_theme.php';$seo=$context->seo();$items=dj_items($context);$pagination=$context->get('pagination',[]);$classicTotal=(is_array($pagination)&&isset($pagination['total']))?(int)$pagination['total']:count($items);
?><!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= $context->e((string)($seo['title']??$context->get('site_name','清静无为'))) ?></title><?php if(!empty($seo['description'])):?><meta name="description" content="<?= $context->e((string)$seo['description']) ?>"><?php endif;?><link rel="stylesheet" href="<?= $context->e($context->asset('css/style.css')) ?>"></head><body class="dj-theme">
<?php require dirname(__DIR__).'/partials/header.php';?>
<main><section class="dj-hero" id="altar"><img class="dj-bg" src="<?= $context->e($context->asset('images/bg-temple.webp')) ?>" alt="" aria-hidden="true"><div class="dj-vignette"></div>
<div class="dj-taiji" aria-hidden="true"><img class="dj-taiji-outer" src="<?= $context->e($context->asset('images/taiji-outer.png')) ?>" alt=""><img class="dj-taiji-inner" src="<?= $context->e($context->asset('images/taiji-inner.png')) ?>" alt=""></div>
<button class="dj-taiji-eye" type="button" aria-label="阵眼，开启玄门"></button><span class="dj-eye-hint" aria-hidden="true">触阵眼 · 开玄门</span>
<div class="dj-xuanmen" aria-hidden="true"><div class="dj-xuanmen-taiji"><img src="<?= $context->e($context->asset('images/taiji-simple.svg')) ?>" alt=""></div><i class="dj-taiji-half left" aria-hidden="true"></i><i class="dj-taiji-half right" aria-hidden="true"></i></div>
<div class="dj-sanqing" aria-label="三清"><img src="<?= $context->e($context->asset('images/lingbao.png')) ?>" alt="上清灵宝天尊"><img class="dj-center" src="<?= $context->e($context->asset('images/yuanshi.png')) ?>" alt="玉清元始天尊"><img src="<?= $context->e($context->asset('images/daode.png')) ?>" alt="太清道德天尊"><div class="dj-sanqing-names" aria-hidden="true"><span>灵宝天尊</span><span>元始天尊</span><span>道德天尊</span></div></div>
<div class="dj-altar-furniture" aria-hidden="true"><img class="dj-altar-table-image" src="<?= $context->e($context->asset('images/altar-table.png')) ?>" alt=""></div>
<div class="dj-hero-smoke" aria-hidden="true"><i class="dj-wisp w1"></i><i class="dj-wisp w2"></i><i class="dj-wisp w3"></i><i class="dj-wisp w4"></i></div><div class="dj-altar"><button class="dj-artifact dj-bell" data-artifact="bell" aria-label="三清铃"><img src="<?= $context->e($context->asset('images/bell.png')) ?>" alt=""></button><em class="dj-artifact-label label-bell">三清铃</em><button class="dj-artifact dj-sword" data-artifact="sword" aria-label="法剑"><i class="dj-sword-short-spark" aria-hidden="true"></i><img src="<?= $context->e($context->asset('images/sword.png')) ?>" alt=""></button><em class="dj-artifact-label label-sword">玄天法剑</em><button class="dj-incense" type="button" aria-label="点击敬香"><img src="<?= $context->e($context->asset('images/incense.png')) ?>" alt="香炉"><img class="dj-smoke" src="<?= $context->e($context->asset('images/smoke.png')) ?>" alt=""><i class="dj-incense-sticks" aria-hidden="true"><i></i><i></i><i></i></i><i class="dj-flames"><i class="dj-flame f1"></i><i class="dj-flame f2"></i><i class="dj-flame f3"></i></i><span>敬香</span></button><em class="dj-artifact-label label-incense">清香袅袅</em><button class="dj-artifact dj-bagua" data-artifact="bagua" aria-label="八卦镜"><i class="dj-bagua-dao" aria-hidden="true">道</i><i class="dj-static-trigrams" aria-hidden="true"><b class="qian">乾</b><b class="dui">兑</b><b class="li">离</b><b class="zhen">震</b><b class="xun">巽</b><b class="kan">坎</b><b class="gen">艮</b><b class="kun">坤</b></i><img src="<?= $context->e($context->asset('images/bagua.png')) ?>" alt=""></button><em class="dj-artifact-label label-bagua">八卦镜</em><button class="dj-artifact dj-talisman" data-artifact="talisman" aria-label="符箓"><i class="dj-talisman-stand" aria-hidden="true"></i><i class="dj-talisman-aura" aria-hidden="true"></i><img src="<?= $context->e($context->asset('images/talisman.png')) ?>" alt=""></button><em class="dj-artifact-label label-talisman">符箓</em></div>
<a class="dj-scroll" href="#classics">典籍与心悟 ↓</a></section>
<section class="dj-classics" id="classics"><div class="dj-section-title"><span></span><h2><?= $context->e((string)$context->setting('section_title','典籍与心悟')) ?></h2><span></span></div>
<?php if($items===[]):?><p class="dj-empty">万物静观，暂无篇章。</p><?php else:?><div class="dj-classics-meta" aria-live="polite"><span>共 <?= $context->e((string)$classicTotal) ?> 篇</span><span class="dj-classics-page-status"></span></div><div class="dj-grid dj-classics-grid" data-page-size="10"><?php foreach($items as $index=>$item):$url=dj_content_url($item);?><article class="dj-card dj-classic-card" data-classic-index="<?= $context->e((string)$index) ?>"><?php if(($cover=dj_cover($item))!==''):?><a href="<?= $context->e($url) ?>"><img class="dj-card-cover" src="<?= $context->e($cover) ?>" alt=""></a><?php endif;?><div><time><?= $context->e(dj_date($item['published_at']??$item['created_at']??'')) ?></time><h3><a href="<?= $context->e($url) ?>"><?= $context->e((string)($item['title']??'')) ?></a></h3><?php if(dj_excerpt($item)!==''):?><p><?= $context->e(dj_excerpt($item)) ?></p><?php endif;?><a class="dj-read" href="<?= $context->e($url) ?>">阅读全文 →</a></div></article><?php endforeach;?></div><?php if(is_array($pagination)&&!empty($pagination['pages'])):?><nav class="dj-pagination dj-home-pagination dj-server-pagination" aria-label="典籍分页"><?php foreach($pagination['pages'] as $p):$purl=(string)($p['url']??'');$plabel=(string)($p['label']??$p['page']??'');?><a href="<?= $context->e($purl) ?>#classics"<?= !empty($p['current'])?' aria-current="page"':'' ?>><?= $context->e($plabel) ?></a><?php endforeach;?></nav><?php else:?><nav class="dj-pagination dj-home-pagination" aria-label="典籍分页"></nav><?php endif;?><?php endif;?></section></main>
<div class="dj-stage" hidden aria-live="polite">
  <div class="dj-stage-shade"></div>
  <div class="dj-stage-fx"></div>
  <div class="dj-stage-object"></div>
  <div class="dj-stage-name"></div>
  <button class="dj-stage-close" type="button" aria-label="关闭法器演出">×</button>
</div>
<?php require dirname(__DIR__).'/partials/footer.php';?><script defer src="<?= $context->e($context->asset('js/daojia.js')) ?>"></script></body></html>